# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.extraModprobeConfig = ''
    # Maybe get suspend-then-hibernate working?
    options rtc_cmos use_acpi_alarm=1
  '';

  # NVIDIA open drivers
  hardware.graphics.enable = true;
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia.open = true;

  # Required for wayland on nvidia graphics
  hardware.nvidia.modesetting.enable = true;

  # Without this the driver drops VRAM contents across suspend, so the GPU comes
  # back with stale state and modesets fail ("Flip event timeout on head N").
  hardware.nvidia.powerManagement.enable = true;

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/12ec02d1-e496-48b3-9ea7-14d2d7a39de5";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/6ADD-752B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/work" =
    {
      device = "/dev/disk/by-uuid/b1fc5e16-9883-4701-9fe3-113f6b011fb2";
      fsType = "ext4";
    };

  fileSystems."/mnt/other" =
    {
      device = "/dev/disk/by-uuid/d1dddc00-45ec-44de-bc5b-727d1396b211";
      fsType = "ext4";
    };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
